
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ccss;

import java_cup.runtime.*;
import java.util.ArrayList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class SintacticoCCSS extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public SintacticoCCSS() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public SintacticoCCSS(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SintacticoCCSS(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\045\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\006\000\002\005\004" +
    "\000\002\005\003\000\002\015\010\000\002\015\010\000" +
    "\002\006\004\000\002\006\003\000\002\007\006\000\002" +
    "\007\006\000\002\007\006\000\002\007\006\000\002\007" +
    "\006\000\002\007\006\000\002\007\012\000\002\007\006" +
    "\000\002\007\014\000\002\007\006\000\002\007\006\000" +
    "\002\010\003\000\002\010\003\000\002\010\003\000\002" +
    "\010\003\000\002\011\005\000\002\011\003\000\002\012" +
    "\003\000\002\012\003\000\002\012\003\000\002\012\003" +
    "\000\002\012\003\000\002\013\003\000\002\013\003\000" +
    "\002\014\003\000\002\014\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\140\000\004\040\007\001\002\000\006\002\000\040" +
    "\007\001\002\000\006\002\ufffe\040\ufffe\001\002\000\004" +
    "\002\141\001\002\000\004\041\010\001\002\000\006\032" +
    "\012\033\014\001\002\000\010\032\012\033\014\042\137" +
    "\001\002\000\004\060\132\001\002\000\010\032\ufffb\033" +
    "\ufffb\042\ufffb\001\002\000\004\060\015\001\002\000\004" +
    "\040\016\001\002\000\004\061\017\001\002\000\004\051" +
    "\020\001\002\000\030\004\024\005\031\012\034\020\030" +
    "\021\027\022\026\023\035\024\022\027\021\030\025\031" +
    "\023\001\002\000\004\037\121\001\002\000\004\037\116" +
    "\001\002\000\004\037\113\001\002\000\004\037\110\001" +
    "\002\000\004\037\105\001\002\000\004\037\102\001\002" +
    "\000\004\037\077\001\002\000\004\037\074\001\002\000" +
    "\004\037\065\001\002\000\036\004\ufff7\005\ufff7\012\ufff7" +
    "\020\ufff7\021\ufff7\022\ufff7\023\ufff7\024\ufff7\027\ufff7\030" +
    "\ufff7\031\ufff7\032\ufff7\033\ufff7\042\ufff7\001\002\000\036" +
    "\004\024\005\031\012\034\020\030\021\027\022\026\023" +
    "\035\024\022\027\021\030\025\031\023\032\ufff9\033\ufff9" +
    "\042\ufff9\001\002\000\004\037\051\001\002\000\004\037" +
    "\036\001\002\000\004\041\037\001\002\000\006\045\040" +
    "\046\042\001\002\000\010\034\uffdf\042\uffdf\051\uffdf\001" +
    "\002\000\004\034\043\001\002\000\010\034\uffe0\042\uffe0" +
    "\051\uffe0\001\002\000\006\025\045\026\046\001\002\000" +
    "\004\042\047\001\002\000\004\042\uffde\001\002\000\004" +
    "\042\uffdd\001\002\000\004\051\050\001\002\000\036\004" +
    "\ufff0\005\ufff0\012\ufff0\020\ufff0\021\ufff0\022\ufff0\023\ufff0" +
    "\024\ufff0\027\ufff0\030\ufff0\031\ufff0\032\ufff0\033\ufff0\042" +
    "\ufff0\001\002\000\014\013\052\014\055\015\057\016\056" +
    "\017\060\001\002\000\006\034\uffe5\051\uffe5\001\002\000" +
    "\006\034\061\051\062\001\002\000\006\034\uffe6\051\uffe6" +
    "\001\002\000\006\034\uffe4\051\uffe4\001\002\000\006\034" +
    "\uffe2\051\uffe2\001\002\000\006\034\uffe3\051\uffe3\001\002" +
    "\000\006\034\uffe1\051\uffe1\001\002\000\014\013\052\014" +
    "\055\015\057\016\056\017\060\001\002\000\036\004\ufff4" +
    "\005\ufff4\012\ufff4\020\ufff4\021\ufff4\022\ufff4\023\ufff4\024" +
    "\ufff4\027\ufff4\030\ufff4\031\ufff4\032\ufff4\033\ufff4\042\ufff4" +
    "\001\002\000\006\034\uffe7\051\uffe7\001\002\000\036\004" +
    "\ufff8\005\ufff8\012\ufff8\020\ufff8\021\ufff8\022\ufff8\023\ufff8" +
    "\024\ufff8\027\ufff8\030\ufff8\031\ufff8\032\ufff8\033\ufff8\042" +
    "\ufff8\001\002\000\012\006\070\007\067\010\072\011\071" +
    "\001\002\000\004\051\073\001\002\000\004\051\uffea\001" +
    "\002\000\004\051\uffeb\001\002\000\004\051\uffe8\001\002" +
    "\000\004\051\uffe9\001\002\000\036\004\ufff6\005\ufff6\012" +
    "\ufff6\020\ufff6\021\ufff6\022\ufff6\023\ufff6\024\ufff6\027\ufff6" +
    "\030\ufff6\031\ufff6\032\ufff6\033\ufff6\042\ufff6\001\002\000" +
    "\004\055\075\001\002\000\004\051\076\001\002\000\036" +
    "\004\ufff3\005\ufff3\012\ufff3\020\ufff3\021\ufff3\022\ufff3\023" +
    "\ufff3\024\ufff3\027\ufff3\030\ufff3\031\ufff3\032\ufff3\033\ufff3" +
    "\042\ufff3\001\002\000\004\053\100\001\002\000\004\051" +
    "\101\001\002\000\036\004\ufff2\005\ufff2\012\ufff2\020\ufff2" +
    "\021\ufff2\022\ufff2\023\ufff2\024\ufff2\027\ufff2\030\ufff2\031" +
    "\ufff2\032\ufff2\033\ufff2\042\ufff2\001\002\000\004\055\103" +
    "\001\002\000\004\051\104\001\002\000\036\004\ufff1\005" +
    "\ufff1\012\ufff1\020\ufff1\021\ufff1\022\ufff1\023\ufff1\024\ufff1" +
    "\027\ufff1\030\ufff1\031\ufff1\032\ufff1\033\ufff1\042\ufff1\001" +
    "\002\000\006\045\040\046\042\001\002\000\004\051\107" +
    "\001\002\000\036\004\uffed\005\uffed\012\uffed\020\uffed\021" +
    "\uffed\022\uffed\023\uffed\024\uffed\027\uffed\030\uffed\031\uffed" +
    "\032\uffed\033\uffed\042\uffed\001\002\000\004\055\111\001" +
    "\002\000\004\051\112\001\002\000\036\004\ufff5\005\ufff5" +
    "\012\ufff5\020\ufff5\021\ufff5\022\ufff5\023\ufff5\024\ufff5\027" +
    "\ufff5\030\ufff5\031\ufff5\032\ufff5\033\ufff5\042\ufff5\001\002" +
    "\000\004\055\114\001\002\000\004\051\115\001\002\000" +
    "\036\004\uffec\005\uffec\012\uffec\020\uffec\021\uffec\022\uffec" +
    "\023\uffec\024\uffec\027\uffec\030\uffec\031\uffec\032\uffec\033" +
    "\uffec\042\uffec\001\002\000\006\045\040\046\042\001\002" +
    "\000\004\051\120\001\002\000\036\004\uffef\005\uffef\012" +
    "\uffef\020\uffef\021\uffef\022\uffef\023\uffef\024\uffef\027\uffef" +
    "\030\uffef\031\uffef\032\uffef\033\uffef\042\uffef\001\002\000" +
    "\004\041\122\001\002\000\004\053\123\001\002\000\004" +
    "\034\124\001\002\000\004\055\125\001\002\000\004\034" +
    "\126\001\002\000\006\045\040\046\042\001\002\000\004" +
    "\042\130\001\002\000\004\051\131\001\002\000\036\004" +
    "\uffee\005\uffee\012\uffee\020\uffee\021\uffee\022\uffee\023\uffee" +
    "\024\uffee\027\uffee\030\uffee\031\uffee\032\uffee\033\uffee\042" +
    "\uffee\001\002\000\004\040\133\001\002\000\004\061\134" +
    "\001\002\000\004\051\135\001\002\000\030\004\024\005" +
    "\031\012\034\020\030\021\027\022\026\023\035\024\022" +
    "\027\021\030\025\031\023\001\002\000\036\004\024\005" +
    "\031\012\034\020\030\021\027\022\026\023\035\024\022" +
    "\027\021\030\025\031\023\032\ufffa\033\ufffa\042\ufffa\001" +
    "\002\000\006\002\ufffd\040\ufffd\001\002\000\010\032\ufffc" +
    "\033\ufffc\042\ufffc\001\002\000\004\002\001\001\002\000" +
    "\006\002\uffff\040\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\140\000\010\002\005\003\003\004\004\001\001\000" +
    "\004\004\141\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\005\010\015\012\001\001\000" +
    "\004\015\137\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\006\032\007\031\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\007\063\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\013\040\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\014\043" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\011\052" +
    "\012\053\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\012\062\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\010\065\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\013\105\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\013\116\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\013\126\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\006" +
    "\135\007\031\001\001\000\004\007\063\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SintacticoCCSS$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SintacticoCCSS$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SintacticoCCSS$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {



    }


// METODOS Y VARIABLES GLOBALES DEL PARSER, PUEDEN SER PUBLICAS O PRIVADAS

public void syntax_error(Symbol s){
/**Metodo al que se llama automaticamente ante algun error sintactico.*/
        System.out.println("Error Sintactico en la Linea " + (s.right+1) +" Columna "+s.left+ ". Identificador " +s.value + " no reconocido." );
int linea = s.right+1; int columna = s.left; 
String texto = "Identificador " +s.value + " no reconocido.";

}            
public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
/**Metodo al que se llama en el momento en que ya no es posible una recuperacion de errores.*/
        System.out.println("Error Sintactico no recuperable en la Linea " + (s.right+1)+ " Columna "+s.left+". Identificador " + s.value + " no reconocido.");
}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$SintacticoCCSS$actions {



  private final SintacticoCCSS parser;

  /** Constructor */
  CUP$SintacticoCCSS$actions(SintacticoCCSS parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$SintacticoCCSS$do_action_part00000000(
    int                        CUP$SintacticoCCSS$act_num,
    java_cup.runtime.lr_parser CUP$SintacticoCCSS$parser,
    java.util.Stack            CUP$SintacticoCCSS$stack,
    int                        CUP$SintacticoCCSS$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SintacticoCCSS$result;

      /* select the action based on the action number */
      switch (CUP$SintacticoCCSS$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).right;
		Caracter start_val = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).value;
		RESULT = start_val;
              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SintacticoCCSS$parser.done_parsing();
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= INSTRUCCION 
            {
              Caracter RESULT =null;
		
              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INSTRUCCION ::= INSTRUCCION BLOQUE 
            {
              Caracter RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).right;
		Caracter i = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).right;
		Caracter n = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.peek()).value;
		
    RESULT = new Caracter();
    NodoCCSS INSTRUCCION = new NodoCCSS("INSTRUCCION");
    INSTRUCCION.insertar(i.nodo); INSTRUCCION.insertar(n.nodo);
    RESULT.nodo = INSTRUCCION;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",1, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // INSTRUCCION ::= BLOQUE 
            {
              Caracter RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).right;
		Caracter n = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.peek()).value;
		
    NodoCCSS INSTRUCCION = new NodoCCSS("INSTRUCCION");
    RESULT = new Caracter();
    INSTRUCCION.insertar(n.nodo); 
    RESULT.nodo = INSTRUCCION;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",1, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // BLOQUE ::= id corcheteA OPCION corcheteC 
            {
              Caracter RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).right;
		Caracter n = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).value;
		
    RESULT = new Caracter();
    NodoCCSS E = new NodoCCSS("BLOQUE");
    E.insertar(new NodoCCSS(i)); E.insertar(new NodoCCSS("[")); E.insertar(n.nodo); E.insertar(new NodoCCSS("]"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("BLOQUE",2, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // OPCION ::= OPCION TIPO 
            {
              Caracter RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).right;
		Caracter i = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).right;
		Caracter n = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.peek()).value;
		
    RESULT = new Caracter();
    NodoCCSS E = new NodoCCSS("OPCION");
    E.insertar(i.nodo); E.insertar(n.nodo);
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("OPCION",3, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // OPCION ::= TIPO 
            {
              Caracter RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).right;
		Caracter n = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.peek()).value;
		
    NodoCCSS E = new NodoCCSS("OPCION");
    RESULT = new Caracter();
    E.insertar(n.nodo); 
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("OPCION",3, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // TIPO ::= grupo parentesisA id parentesisC puntoComa ESTILOS 
            {
              Caracter RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).right;
		Caracter e = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.peek()).value;
		
    RESULT = new Caracter();
    NodoCCSS E = new NodoCCSS("BLOQUE");
    E.insertar(new NodoCCSS("grupo")); E.insertar(new NodoCCSS("(")); E.insertar(new NodoCCSS(i)); E.insertar(new NodoCCSS(")")); 
    E.insertar(e.nodo);
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("TIPO",11, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-5)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // TIPO ::= idd parentesisA id parentesisC puntoComa ESTILOS 
            {
              Caracter RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).right;
		Caracter e = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.peek()).value;
		
    RESULT = new Caracter();
    NodoCCSS E = new NodoCCSS("BLOQUE");
    E.insertar(new NodoCCSS("id")); E.insertar(new NodoCCSS("(")); E.insertar(new NodoCCSS(i)); E.insertar(new NodoCCSS(")")); 
    E.insertar(e.nodo);
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("TIPO",11, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-5)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // ESTILOS ::= ESTILOS ESTILO 
            {
              Caracter RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).right;
		Caracter i = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).right;
		Caracter n = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.peek()).value;
		
    RESULT = new Caracter();
    NodoCCSS E = new NodoCCSS("ESTILOS");
    E.insertar(i.nodo); E.insertar(n.nodo);
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("ESTILOS",4, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // ESTILOS ::= ESTILO 
            {
              Caracter RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).right;
		Caracter n = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.peek()).value;
		
    NodoCCSS E = new NodoCCSS("ESTILOS");
    RESULT = new Caracter();
    E.insertar(n.nodo); 
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("ESTILOS",4, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // ESTILO ::= alineado igual ALINEADO puntoComa 
            {
              Caracter RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).right;
		Caracter v = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).value;
		 //4
    RESULT = new Caracter();
    NodoCCSS E = new NodoCCSS("ESTILO");
    E.insertar(new NodoCCSS("alineado"));E.insertar(new NodoCCSS("=")); E.insertar(v.nodo); E.insertar(new NodoCCSS(";"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("ESTILO",5, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // ESTILO ::= texto igual cadena puntoComa 
            {
              Caracter RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).value;
		 //4
    RESULT = new Caracter();
    NodoCCSS E = new NodoCCSS("ESTILO");
    E.insertar(new NodoCCSS("alineado"));E.insertar(new NodoCCSS("=")); E.insertar(new NodoCCSS(n)); E.insertar(new NodoCCSS(";"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("ESTILO",5, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // ESTILO ::= formato igual FORMATOS puntoComa 
            {
              Caracter RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).right;
		Caracter v = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).value;
		 //4
    RESULT = new Caracter();
    NodoCCSS E = new NodoCCSS("ESTILO");
    E.insertar(new NodoCCSS("alineado"));E.insertar(new NodoCCSS("=")); E.insertar(v.nodo); E.insertar(new NodoCCSS(";"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("ESTILO",5, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // ESTILO ::= letra igual cadena puntoComa 
            {
              Caracter RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).value;
		 //4
    RESULT = new Caracter();
    NodoCCSS E = new NodoCCSS("ESTILO");
    E.insertar(new NodoCCSS("alineado"));E.insertar(new NodoCCSS("="));E.insertar(new NodoCCSS(n));E.insertar(new NodoCCSS(";"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("ESTILO",5, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // ESTILO ::= tamtex igual numero puntoComa 
            {
              Caracter RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).value;
		 //4
    RESULT = new Caracter();
    NodoCCSS E = new NodoCCSS("ESTILO");
    E.insertar(new NodoCCSS("alineado"));E.insertar(new NodoCCSS("=")); E.insertar(new NodoCCSS(n)); E.insertar(new NodoCCSS(";"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("ESTILO",5, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // ESTILO ::= fondo igual cadena puntoComa 
            {
              Caracter RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).value;
		 //4
    RESULT = new Caracter();
    NodoCCSS E = new NodoCCSS("ESTILO");
    E.insertar(new NodoCCSS("alineado"));E.insertar(new NodoCCSS("="));E.insertar(new NodoCCSS(n)); E.insertar(new NodoCCSS(";"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("ESTILO",5, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // ESTILO ::= auto igual corcheteA VALOR coma AREA corcheteC puntoComa 
            {
              Caracter RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-4)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-4)).right;
		Caracter v = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-4)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-2)).right;
		Caracter a = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-2)).value;
		 //8
    RESULT = new Caracter();
    NodoCCSS E = new NodoCCSS("ESTILO");
    E.insertar(new NodoCCSS("auto"));E.insertar(new NodoCCSS("=")); E.insertar(new NodoCCSS("[")); E.insertar(v.nodo);E.insertar(new NodoCCSS(","));
    E.insertar(a.nodo);  E.insertar(new NodoCCSS("]")); E.insertar(new NodoCCSS(";"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("ESTILO",5, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-7)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // ESTILO ::= visible igual VALOR puntoComa 
            {
              Caracter RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).right;
		Caracter v = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).value;
		 //4
    RESULT = new Caracter();
    NodoCCSS E = new NodoCCSS("ESTILO");
    E.insertar(new NodoCCSS("alineado"));E.insertar(new NodoCCSS("=")); E.insertar(v.nodo); E.insertar(new NodoCCSS(";"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("ESTILO",5, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // ESTILO ::= borde igual corcheteA numero coma cadena coma VALOR corcheteC puntoComa 
            {
              Caracter RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-6)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-6)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-6)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-4)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-4)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-2)).right;
		Caracter v = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-2)).value;
		 //10
    RESULT = new Caracter();
    NodoCCSS E = new NodoCCSS("ESTILO");
    E.insertar(new NodoCCSS("borde"));E.insertar(new NodoCCSS("=")); E.insertar(new NodoCCSS("[")); E.insertar(new NodoCCSS(n));E.insertar(new NodoCCSS(","));
    E.insertar(new NodoCCSS(c));  E.insertar(new NodoCCSS(","));  E.insertar(v.nodo);  E.insertar(new NodoCCSS("]")); E.insertar(new NodoCCSS(";"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("ESTILO",5, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-9)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // ESTILO ::= opaque igual VALOR puntoComa 
            {
              Caracter RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).right;
		Caracter v = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).value;
		 //4
    RESULT = new Caracter();
    NodoCCSS E = new NodoCCSS("ESTILO");
    E.insertar(new NodoCCSS("alineado"));E.insertar(new NodoCCSS("=")); E.insertar(v.nodo); E.insertar(new NodoCCSS(";"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("ESTILO",5, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // ESTILO ::= colortext igual cadena puntoComa 
            {
              Caracter RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-1)).value;
		 //4
    RESULT = new Caracter();
    NodoCCSS E = new NodoCCSS("ESTILO");
    E.insertar(new NodoCCSS("alineado"));E.insertar(new NodoCCSS("=")); E.insertar(new NodoCCSS(n)); E.insertar(new NodoCCSS(";"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("ESTILO",5, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // ALINEADO ::= izquierda 
            {
              Caracter RESULT =null;
		
    NodoCCSS E = new NodoCCSS("ALINEADO");
    RESULT = new Caracter();
    E.insertar(new NodoCCSS("izquierda"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("ALINEADO",6, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // ALINEADO ::= derecha 
            {
              Caracter RESULT =null;
		
    NodoCCSS E = new NodoCCSS("ALINEADO");
    RESULT = new Caracter();
    E.insertar(new NodoCCSS("derecha"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("ALINEADO",6, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // ALINEADO ::= centrado 
            {
              Caracter RESULT =null;
		
    NodoCCSS E = new NodoCCSS("ALINEADO");
    RESULT = new Caracter();
    E.insertar(new NodoCCSS("centrado"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("ALINEADO",6, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // ALINEADO ::= justificado 
            {
              Caracter RESULT =null;
		
    NodoCCSS E = new NodoCCSS("ALINEADO");
    RESULT = new Caracter();
    E.insertar(new NodoCCSS("justificado"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("ALINEADO",6, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // FORMATOS ::= FORMATOS coma FORMATO 
            {
              Caracter RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-2)).right;
		Caracter i = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-2)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).right;
		Caracter n = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.peek()).value;
		
    RESULT = new Caracter();
    NodoCCSS E = new NodoCCSS("FORMATOS");
    E.insertar(i.nodo);E.insertar(new NodoCCSS(",")); E.insertar(n.nodo);
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("FORMATOS",7, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.elementAt(CUP$SintacticoCCSS$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // FORMATOS ::= FORMATO 
            {
              Caracter RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()).right;
		Caracter n = (Caracter)((java_cup.runtime.Symbol) CUP$SintacticoCCSS$stack.peek()).value;
		
    NodoCCSS E = new NodoCCSS("FORMATOS");
    RESULT = new Caracter();
    E.insertar(n.nodo); 
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("FORMATOS",7, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // FORMATO ::= negrilla 
            {
              Caracter RESULT =null;
		
    NodoCCSS E = new NodoCCSS("FORMATO");
    RESULT = new Caracter();
    E.insertar(new NodoCCSS("negrilla"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("FORMATO",8, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // FORMATO ::= cursiva 
            {
              Caracter RESULT =null;
		
    NodoCCSS E = new NodoCCSS("FORMATO");
    RESULT = new Caracter();
    E.insertar(new NodoCCSS("cursiva"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("FORMATO",8, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // FORMATO ::= mayuscula 
            {
              Caracter RESULT =null;
		
    NodoCCSS E = new NodoCCSS("FORMATO");
    RESULT = new Caracter();
    E.insertar(new NodoCCSS("mayuscula"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("FORMATO",8, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // FORMATO ::= minuscula 
            {
              Caracter RESULT =null;
		
    NodoCCSS E = new NodoCCSS("FORMATO");
    RESULT = new Caracter();
    E.insertar(new NodoCCSS("minuscula"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("FORMATO",8, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // FORMATO ::= capital 
            {
              Caracter RESULT =null;
		
    NodoCCSS E = new NodoCCSS("FORMATO");
    RESULT = new Caracter();
    E.insertar(new NodoCCSS("capital"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("FORMATO",8, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // VALOR ::= falso 
            {
              Caracter RESULT =null;
		
    NodoCCSS E = new NodoCCSS("VALOR");
    RESULT = new Caracter();
    E.insertar(new NodoCCSS("falso"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("VALOR",9, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // VALOR ::= verdadero 
            {
              Caracter RESULT =null;
		
    NodoCCSS E = new NodoCCSS("VALOR");
    RESULT = new Caracter();
    E.insertar(new NodoCCSS("verdadero"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("VALOR",9, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // AREA ::= horizontal 
            {
              Caracter RESULT =null;
		
    NodoCCSS E = new NodoCCSS("AREA");
    RESULT = new Caracter();
    E.insertar(new NodoCCSS("horizontal"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("AREA",10, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // AREA ::= vertical 
            {
              Caracter RESULT =null;
		
    NodoCCSS E = new NodoCCSS("AREA");
    RESULT = new Caracter();
    E.insertar(new NodoCCSS("vertical"));
    RESULT.nodo = E;

              CUP$SintacticoCCSS$result = parser.getSymbolFactory().newSymbol("AREA",10, ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoCCSS$stack.peek()), RESULT);
            }
          return CUP$SintacticoCCSS$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$SintacticoCCSS$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$SintacticoCCSS$do_action(
    int                        CUP$SintacticoCCSS$act_num,
    java_cup.runtime.lr_parser CUP$SintacticoCCSS$parser,
    java.util.Stack            CUP$SintacticoCCSS$stack,
    int                        CUP$SintacticoCCSS$top)
    throws java.lang.Exception
    {
              return CUP$SintacticoCCSS$do_action_part00000000(
                               CUP$SintacticoCCSS$act_num,
                               CUP$SintacticoCCSS$parser,
                               CUP$SintacticoCCSS$stack,
                               CUP$SintacticoCCSS$top);
    }
}

}
