
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ccss;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int mayuscula = 11;
  public static final int fondo = 16;
  public static final int opaque = 22;
  public static final int dosPuntos = 34;
  public static final int idd = 25;
  public static final int negrilla = 9;
  public static final int corcheteC = 32;
  public static final int corcheteA = 31;
  public static final int coma = 26;
  public static final int derecha = 5;
  public static final int igual = 29;
  public static final int letra = 14;
  public static final int auto = 17;
  public static final int caracter = 45;
  public static final int grupo = 24;
  public static final int dividido = 42;
  public static final int alineado = 3;
  public static final int tamtex = 15;
  public static final int numero = 41;
  public static final int justificado = 7;
  public static final int vertical = 20;
  public static final int menos = 28;
  public static final int visible = 18;
  public static final int EOF = 0;
  public static final int mas = 27;
  public static final int verdadero = 35;
  public static final int error = 1;
  public static final int capital = 13;
  public static final int horizontal = 19;
  public static final int por = 33;
  public static final int punto = 44;
  public static final int ERROR = 40;
  public static final int llaveC = 38;
  public static final int minuscula = 12;
  public static final int id = 30;
  public static final int puntoComa = 39;
  public static final int llaveA = 37;
  public static final int falso = 36;
  public static final int colortext = 23;
  public static final int centrado = 6;
  public static final int texto = 2;
  public static final int izquierda = 4;
  public static final int formato = 8;
  public static final int parentesisC = 47;
  public static final int borde = 21;
  public static final int parentesisA = 46;
  public static final int cursiva = 10;
  public static final int cadena = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "texto",
  "alineado",
  "izquierda",
  "derecha",
  "centrado",
  "justificado",
  "formato",
  "negrilla",
  "cursiva",
  "mayuscula",
  "minuscula",
  "capital",
  "letra",
  "tamtex",
  "fondo",
  "auto",
  "visible",
  "horizontal",
  "vertical",
  "borde",
  "opaque",
  "colortext",
  "grupo",
  "idd",
  "coma",
  "mas",
  "menos",
  "igual",
  "id",
  "corcheteA",
  "corcheteC",
  "por",
  "dosPuntos",
  "verdadero",
  "falso",
  "llaveA",
  "llaveC",
  "puntoComa",
  "ERROR",
  "numero",
  "dividido",
  "cadena",
  "punto",
  "caracter",
  "parentesisA",
  "parentesisC"
  };
}

