/* The following code was generated by JFlex 1.6.1 */

package chtml;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/Aroche/Documents/NetBeansProjects/UsacWeb/src/chtml/LexicoCHTML.jflex</tt>
 */
public class LexicoCHTML implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\23\1\6\1\57\1\57\1\5\22\0\1\23\1\0\1\3"+
    "\4\0\1\0\1\52\1\53\3\0\1\35\1\56\1\11\1\2\11\2"+
    "\1\0\1\54\1\10\1\55\1\12\2\0\1\17\1\20\1\24\1\37"+
    "\1\21\1\31\1\50\1\25\1\33\1\41\1\47\1\30\1\27\1\34"+
    "\1\40\1\43\1\1\1\22\1\16\1\26\1\42\1\51\1\1\1\45"+
    "\1\1\1\36\1\0\1\7\2\0\1\44\1\0\1\17\1\20\1\24"+
    "\1\37\1\21\1\31\1\50\1\25\1\33\1\41\1\47\1\30\1\27"+
    "\1\34\1\40\1\43\1\1\1\22\1\16\1\26\1\42\1\51\1\1"+
    "\1\45\1\1\1\36\1\0\1\4\10\0\1\57\73\0\1\1\7\0"+
    "\1\1\3\0\1\1\5\0\1\1\6\0\1\1\6\0\1\1\7\0"+
    "\1\1\3\0\1\1\5\0\1\1\6\0\1\1\65\0\2\32\115\0"+
    "\1\15\u1e9c\0\1\13\1\14\12\0\1\57\1\57\u0100\0\1\46\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udee5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\4\1\10\2"+
    "\1\1\5\2\1\5\1\6\1\7\1\10\2\0\1\11"+
    "\11\0\1\11\2\0\10\2\1\12\1\13\3\2\1\0"+
    "\1\2\1\0\2\2\1\0\1\14\1\2\1\14\4\2"+
    "\1\15\7\0\2\16\4\0\3\2\1\0\6\2\1\0"+
    "\3\2\1\0\1\2\2\0\3\2\1\0\5\2\5\0"+
    "\1\17\10\0\2\2\1\20\1\0\4\2\1\21\1\22"+
    "\1\0\3\2\1\0\1\2\2\0\2\2\1\0\1\2"+
    "\1\0\4\2\3\0\1\23\6\0\1\24\2\0\2\2"+
    "\1\0\1\2\1\25\1\26\2\2\2\27\1\30\1\31"+
    "\1\0\1\2\1\32\11\0\1\32\1\33\1\0\1\2"+
    "\1\0\1\2\1\34\1\35\1\36\15\0\1\2\1\0"+
    "\1\2\1\37\2\2\2\40\4\0\1\41\1\42\7\0"+
    "\2\43\2\44\1\45\1\0\1\46\1\47\4\0\1\50"+
    "\2\0\2\51\1\0\2\2\1\52\22\0\2\53\1\2"+
    "\3\0\1\54\15\0\1\55\1\2\1\0\1\56\2\0"+
    "\1\57\1\60\1\0\1\61\2\0\1\62\5\0\1\63"+
    "\1\64\1\0\1\65\2\0\1\66\1\67\1\70\2\0"+
    "\1\71\1\0\1\72\1\73\1\0\1\74\1\75\1\0"+
    "\1\76\4\0\1\77\1\0\1\100";

  private static int [] zzUnpackAction() {
    int [] result = new int[335];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\60\0\360\0\u0120"+
    "\0\u0150\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240\0\u0270\0\u02a0"+
    "\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0\0\u03f0\0\u0420"+
    "\0\60\0\60\0\60\0\60\0\u0450\0\300\0\60\0\u0480"+
    "\0\u04b0\0\u04e0\0\u0510\0\u0540\0\u0570\0\u05a0\0\u0150\0\u05d0"+
    "\0\u0150\0\u0600\0\u0630\0\u0660\0\u0690\0\u06c0\0\u06f0\0\u0720"+
    "\0\u0750\0\u0780\0\u07b0\0\140\0\140\0\u07e0\0\u0810\0\u0840"+
    "\0\u0870\0\u08a0\0\u08d0\0\u0900\0\u0930\0\u0960\0\60\0\u0990"+
    "\0\140\0\u09c0\0\u09f0\0\u0a20\0\u0a50\0\u0450\0\u0a80\0\u0ab0"+
    "\0\u0ae0\0\u0b10\0\u0b40\0\u0b70\0\u0ba0\0\60\0\u0bd0\0\u0c00"+
    "\0\u0c30\0\u0c60\0\u0c90\0\u0cc0\0\u0cf0\0\u0d20\0\u0d50\0\u0d80"+
    "\0\u0db0\0\u0de0\0\u0e10\0\u0e40\0\u0e70\0\u0ea0\0\u0ed0\0\u0f00"+
    "\0\u0f30\0\u0f60\0\u0f90\0\u0fc0\0\u0ff0\0\u1020\0\u1050\0\u1080"+
    "\0\u10b0\0\u10e0\0\u1110\0\u1140\0\u1170\0\u11a0\0\u11d0\0\u1200"+
    "\0\u1230\0\u1260\0\u1290\0\60\0\u12c0\0\u12f0\0\u1320\0\u1350"+
    "\0\u1380\0\u13b0\0\u13e0\0\u1410\0\u1440\0\u1470\0\140\0\u14a0"+
    "\0\u14d0\0\u1500\0\u1530\0\u1560\0\140\0\u1590\0\u15c0\0\u15f0"+
    "\0\u1620\0\u1650\0\u1680\0\u16b0\0\u16e0\0\u1710\0\u1740\0\u1770"+
    "\0\u17a0\0\u17d0\0\u1800\0\u1830\0\u1860\0\u1890\0\u18c0\0\u18f0"+
    "\0\u1920\0\u1950\0\60\0\u1980\0\u19b0\0\u19e0\0\u1a10\0\u1a40"+
    "\0\u1a70\0\60\0\u1aa0\0\u1ad0\0\u1b00\0\u1b30\0\u1b60\0\u1b90"+
    "\0\140\0\140\0\u1bc0\0\u1bf0\0\60\0\140\0\140\0\u1c20"+
    "\0\u1c50\0\u1c80\0\60\0\u1cb0\0\u1ce0\0\u1d10\0\u1d40\0\u1d70"+
    "\0\u1da0\0\u1dd0\0\u1e00\0\u1e30\0\140\0\140\0\u1e60\0\u1e90"+
    "\0\u1ec0\0\u1ef0\0\140\0\140\0\140\0\u1f20\0\u1f50\0\u1f80"+
    "\0\u1fb0\0\u1fe0\0\u2010\0\u2040\0\u2070\0\u20a0\0\u0bd0\0\u20d0"+
    "\0\u2100\0\u2130\0\u2160\0\u2190\0\u21c0\0\140\0\u21f0\0\u2220"+
    "\0\60\0\140\0\u2250\0\u2280\0\u22b0\0\u22e0\0\60\0\60"+
    "\0\u2310\0\u2340\0\u2370\0\u23a0\0\u23d0\0\u2400\0\u2430\0\60"+
    "\0\140\0\60\0\140\0\60\0\u2460\0\60\0\60\0\u2490"+
    "\0\u24c0\0\u24f0\0\u2520\0\u0bd0\0\u2550\0\u2580\0\60\0\140"+
    "\0\u25b0\0\u25e0\0\u2610\0\140\0\u2640\0\u2670\0\u26a0\0\u26d0"+
    "\0\u2700\0\u2730\0\u2760\0\u2790\0\u27c0\0\u27f0\0\u2820\0\u2850"+
    "\0\u2880\0\u28b0\0\u28e0\0\u2910\0\u2940\0\u2970\0\60\0\140"+
    "\0\u29a0\0\u29d0\0\u2a00\0\u2a30\0\u2a60\0\u2a90\0\u2ac0\0\u2af0"+
    "\0\u2b20\0\u2b50\0\u2b80\0\u2bb0\0\u2be0\0\u2c10\0\u2c40\0\u2c70"+
    "\0\u2ca0\0\u2cd0\0\60\0\u2d00\0\u2d30\0\60\0\u2d60\0\u2d90"+
    "\0\60\0\u2dc0\0\u2df0\0\60\0\u2e20\0\u2e50\0\60\0\u2e80"+
    "\0\u2eb0\0\u2ee0\0\u2f10\0\u2f40\0\60\0\140\0\u2f70\0\60"+
    "\0\u2fa0\0\u2fd0\0\60\0\60\0\60\0\u3000\0\u3030\0\60"+
    "\0\u3060\0\60\0\60\0\u3090\0\60\0\60\0\u30c0\0\60"+
    "\0\u30f0\0\u3120\0\u3150\0\u3180\0\60\0\u31b0\0\60";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[335];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\2\2\6\1\2\1\7"+
    "\1\2\1\10\2\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\6\1\20\1\3\1\21\2\3\1\22\1\23"+
    "\1\24\1\3\1\2\2\3\1\25\2\3\1\26\2\3"+
    "\1\2\1\3\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\2\62\0\2\3\13\0\5\3\1\0\6\3\1\0"+
    "\2\3\1\0\10\3\1\0\3\3\10\0\1\4\53\0"+
    "\1\35\1\0\3\36\1\37\54\36\11\0\1\40\7\0"+
    "\1\41\2\0\1\42\4\0\1\43\26\0\5\44\2\45"+
    "\1\44\1\46\47\44\3\47\4\50\5\47\1\51\43\47"+
    "\17\0\1\52\23\0\1\53\15\0\2\3\13\0\1\3"+
    "\1\54\3\3\1\0\6\3\1\0\2\3\1\0\5\3"+
    "\1\55\2\3\1\0\3\3\7\0\2\3\13\0\5\3"+
    "\1\0\4\3\1\56\1\3\1\0\1\3\1\57\1\0"+
    "\10\3\1\0\3\3\7\0\2\3\13\0\5\3\1\0"+
    "\6\3\1\0\2\3\1\0\2\3\1\60\5\3\1\0"+
    "\3\3\7\0\2\3\13\0\5\3\1\0\6\3\1\0"+
    "\1\3\1\61\1\0\10\3\1\0\3\3\7\0\2\3"+
    "\13\0\5\3\1\0\6\3\1\0\2\3\1\0\4\3"+
    "\1\62\3\3\1\0\3\3\7\0\2\3\13\0\1\3"+
    "\1\63\1\64\2\3\1\0\2\3\1\65\1\3\1\66"+
    "\1\3\1\0\2\3\1\0\10\3\1\0\3\3\7\0"+
    "\2\3\13\0\1\3\1\67\1\3\1\70\1\3\1\0"+
    "\6\3\1\71\1\72\1\3\1\0\10\3\1\0\3\3"+
    "\7\0\2\3\13\0\5\3\1\0\6\3\1\73\1\74"+
    "\1\3\1\0\2\3\1\75\5\3\1\0\3\3\35\0"+
    "\1\76\7\0\1\77\21\0\2\3\13\0\5\3\1\0"+
    "\3\3\1\100\2\3\1\0\2\3\1\0\1\3\1\101"+
    "\6\3\1\0\3\3\7\0\2\3\13\0\5\3\1\0"+
    "\6\3\1\0\2\3\1\0\5\3\1\102\2\3\1\0"+
    "\3\3\7\0\2\3\13\0\1\3\1\103\3\3\1\0"+
    "\6\3\1\0\2\3\1\0\10\3\1\0\3\3\7\0"+
    "\2\3\13\0\4\3\1\104\1\0\6\3\1\0\2\3"+
    "\1\0\10\3\1\0\3\3\7\0\2\3\13\0\1\3"+
    "\1\105\3\3\1\0\6\3\1\0\2\3\1\0\10\3"+
    "\1\0\3\3\10\0\1\106\66\0\1\107\102\0\1\110"+
    "\47\0\1\111\1\112\13\0\1\113\1\114\47\0\2\115"+
    "\24\0\10\44\1\116\47\44\10\45\1\117\47\45\31\0"+
    "\1\120\26\0\14\50\1\37\43\50\20\0\1\121\7\0"+
    "\1\122\61\0\2\123\25\0\2\3\13\0\5\3\1\0"+
    "\4\3\1\124\1\3\1\0\2\3\1\0\10\3\1\0"+
    "\3\3\7\0\2\3\13\0\5\3\1\0\6\3\1\123"+
    "\1\125\1\3\1\0\10\3\1\0\3\3\7\0\2\3"+
    "\13\0\5\3\1\0\2\3\1\126\3\3\1\127\1\130"+
    "\1\3\1\0\10\3\1\0\3\3\7\0\2\3\13\0"+
    "\5\3\1\0\1\131\5\3\1\0\2\3\1\0\10\3"+
    "\1\0\3\3\7\0\2\3\13\0\5\3\1\0\2\3"+
    "\1\132\3\3\1\0\2\3\1\0\10\3\1\0\3\3"+
    "\7\0\2\3\13\0\5\3\1\0\4\3\1\133\1\3"+
    "\1\0\2\3\1\0\10\3\1\0\3\3\7\0\2\3"+
    "\13\0\5\3\1\0\2\3\1\134\3\3\1\0\2\3"+
    "\1\0\10\3\1\0\3\3\7\0\2\3\13\0\5\3"+
    "\1\0\6\3\1\0\2\3\1\0\3\3\1\135\4\3"+
    "\1\0\3\3\7\0\2\3\13\0\5\3\1\0\6\3"+
    "\1\136\1\137\1\3\1\0\10\3\1\0\3\3\7\0"+
    "\2\3\13\0\2\3\1\140\2\3\1\0\6\3\1\0"+
    "\2\3\1\0\10\3\1\0\3\3\7\0\2\3\13\0"+
    "\5\3\1\0\6\3\1\0\2\3\1\0\7\3\1\141"+
    "\1\0\3\3\34\0\1\142\32\0\2\3\13\0\5\3"+
    "\1\0\2\3\1\143\3\3\1\0\2\3\1\0\10\3"+
    "\1\0\3\3\36\0\1\144\3\0\1\145\24\0\2\3"+
    "\13\0\5\3\1\0\4\3\1\146\1\3\1\0\1\3"+
    "\1\147\1\0\10\3\1\0\3\3\7\0\2\3\13\0"+
    "\5\3\1\0\6\3\1\0\1\3\1\150\1\0\10\3"+
    "\1\0\3\3\25\0\1\151\41\0\2\3\13\0\1\3"+
    "\1\152\3\3\1\0\6\3\1\0\2\3\1\0\10\3"+
    "\1\0\3\3\7\0\2\3\13\0\5\3\1\0\1\153"+
    "\5\3\1\0\2\3\1\0\10\3\1\0\3\3\7\0"+
    "\2\3\13\0\5\3\1\0\6\3\1\0\1\3\1\154"+
    "\1\0\10\3\1\0\3\3\7\0\2\3\13\0\5\3"+
    "\1\0\6\3\1\0\2\3\1\0\4\3\1\155\3\3"+
    "\1\0\3\3\7\0\2\3\13\0\5\3\1\0\4\3"+
    "\1\156\1\3\1\0\2\3\1\0\10\3\1\0\3\3"+
    "\6\0\11\157\1\160\46\157\24\0\1\161\50\0\2\162"+
    "\67\0\1\163\46\0\2\164\62\0\1\165\72\0\1\166"+
    "\30\0\1\167\1\170\103\0\2\171\45\0\1\172\64\0"+
    "\1\173\65\0\1\174\24\0\2\3\13\0\5\3\1\0"+
    "\2\3\1\175\3\3\1\0\2\3\1\0\10\3\1\0"+
    "\3\3\7\0\2\3\13\0\5\3\1\0\6\3\1\0"+
    "\1\3\1\176\1\0\10\3\1\0\3\3\7\0\2\3"+
    "\13\0\5\3\1\0\6\3\1\0\2\3\1\0\2\3"+
    "\1\177\5\3\1\0\3\3\42\0\1\200\24\0\2\3"+
    "\13\0\5\3\1\0\6\3\1\0\1\3\1\201\1\0"+
    "\10\3\1\0\3\3\7\0\2\3\13\0\5\3\1\0"+
    "\1\3\1\202\4\3\1\0\2\3\1\0\10\3\1\0"+
    "\3\3\7\0\2\3\13\0\5\3\1\0\6\3\1\0"+
    "\2\3\1\0\2\3\1\203\5\3\1\0\3\3\7\0"+
    "\2\3\13\0\1\3\1\204\3\3\1\0\6\3\1\0"+
    "\2\3\1\0\10\3\1\0\3\3\7\0\2\3\13\0"+
    "\1\3\1\205\3\3\1\0\6\3\1\0\2\3\1\0"+
    "\10\3\1\0\3\3\7\0\2\3\13\0\1\3\1\206"+
    "\3\3\1\0\6\3\1\0\2\3\1\0\10\3\1\0"+
    "\3\3\32\0\1\207\34\0\2\3\13\0\5\3\1\0"+
    "\1\210\5\3\1\0\2\3\1\0\10\3\1\0\3\3"+
    "\7\0\2\3\13\0\5\3\1\0\4\3\1\211\1\3"+
    "\1\0\2\3\1\0\10\3\1\0\3\3\7\0\2\3"+
    "\13\0\5\3\1\0\2\3\1\212\3\3\1\0\2\3"+
    "\1\0\10\3\1\0\3\3\50\0\1\213\16\0\2\3"+
    "\13\0\5\3\1\0\6\3\1\0\2\3\1\0\4\3"+
    "\1\214\3\3\1\0\3\3\52\0\1\215\50\0\1\216"+
    "\23\0\2\3\13\0\5\3\1\0\6\3\1\0\2\3"+
    "\1\0\6\3\1\217\1\3\1\0\3\3\7\0\2\3"+
    "\13\0\5\3\1\0\6\3\1\0\2\3\1\216\10\3"+
    "\1\0\3\3\7\0\2\3\13\0\5\3\1\0\6\3"+
    "\1\0\2\3\1\0\1\3\1\220\6\3\1\0\3\3"+
    "\56\0\1\221\10\0\2\3\13\0\5\3\1\0\6\3"+
    "\1\0\2\3\1\0\10\3\1\0\1\3\1\222\1\3"+
    "\7\0\2\3\13\0\5\3\1\0\6\3\1\223\1\224"+
    "\1\3\1\0\10\3\1\0\3\3\7\0\2\3\13\0"+
    "\3\3\1\225\1\3\1\0\6\3\1\0\2\3\1\0"+
    "\10\3\1\0\3\3\7\0\2\3\13\0\5\3\1\0"+
    "\6\3\1\0\2\3\1\0\5\3\1\226\2\3\1\0"+
    "\3\3\7\0\2\3\13\0\5\3\1\0\6\3\1\0"+
    "\2\3\1\0\2\3\1\227\5\3\1\0\3\3\6\0"+
    "\11\157\1\230\46\157\11\0\1\231\65\0\1\232\55\0"+
    "\2\233\70\0\1\234\52\0\1\235\72\0\1\236\30\0"+
    "\1\237\2\0\1\240\57\0\1\240\102\0\1\241\45\0"+
    "\1\242\75\0\1\243\53\0\1\244\24\0\2\3\13\0"+
    "\5\3\1\0\6\3\1\0\2\3\1\0\2\3\1\245"+
    "\5\3\1\0\3\3\7\0\2\3\13\0\5\3\1\0"+
    "\6\3\1\0\1\3\1\246\1\0\10\3\1\0\3\3"+
    "\27\0\1\247\37\0\2\3\13\0\3\3\1\250\1\3"+
    "\1\0\6\3\1\0\2\3\1\0\10\3\1\0\3\3"+
    "\7\0\2\3\13\0\5\3\1\0\6\3\1\0\2\3"+
    "\1\0\2\3\1\251\5\3\1\0\3\3\7\0\2\3"+
    "\13\0\5\3\1\0\6\3\1\0\1\3\1\252\1\0"+
    "\10\3\1\0\3\3\7\0\2\3\13\0\5\3\1\0"+
    "\1\253\5\3\1\0\2\3\1\0\10\3\1\0\3\3"+
    "\7\0\2\3\13\0\5\3\1\0\6\3\1\0\2\3"+
    "\1\0\6\3\1\254\1\3\1\0\3\3\54\0\2\255"+
    "\11\0\2\3\13\0\5\3\1\0\6\3\1\0\2\3"+
    "\1\0\10\3\1\255\1\256\2\3\7\0\2\3\13\0"+
    "\1\3\1\257\3\3\1\0\6\3\1\0\2\3\1\0"+
    "\10\3\1\0\3\3\7\0\2\3\13\0\5\3\1\0"+
    "\6\3\1\0\2\3\1\0\2\3\1\260\5\3\1\0"+
    "\3\3\36\0\1\261\30\0\2\3\13\0\5\3\1\0"+
    "\4\3\1\262\1\3\1\0\2\3\1\0\10\3\1\0"+
    "\3\3\34\0\1\263\46\0\2\264\1\0\1\265\1\266"+
    "\2\0\1\267\1\0\1\270\2\0\1\271\2\272\4\0"+
    "\1\273\2\0\1\274\15\0\2\3\13\0\5\3\1\0"+
    "\2\3\1\275\3\3\1\0\2\3\1\0\10\3\1\0"+
    "\3\3\7\0\2\3\13\0\5\3\1\0\6\3\1\0"+
    "\2\3\1\0\2\3\1\276\5\3\1\0\3\3\27\0"+
    "\1\277\37\0\2\3\13\0\3\3\1\300\1\3\1\0"+
    "\6\3\1\0\2\3\1\0\10\3\1\0\3\3\46\0"+
    "\1\301\20\0\2\3\13\0\5\3\1\0\6\3\1\0"+
    "\2\3\1\0\2\3\1\302\5\3\1\0\3\3\7\0"+
    "\2\3\13\0\5\3\1\0\4\3\1\303\1\3\1\0"+
    "\2\3\1\0\10\3\1\0\3\3\7\0\2\3\13\0"+
    "\5\3\1\0\6\3\1\0\2\3\1\0\2\3\1\304"+
    "\5\3\1\0\3\3\7\0\2\3\13\0\4\3\1\305"+
    "\1\0\6\3\1\0\2\3\1\0\10\3\1\0\3\3"+
    "\6\0\11\157\1\306\46\157\11\0\1\307\66\0\1\310"+
    "\67\0\1\311\72\0\1\312\35\0\1\313\2\0\1\314"+
    "\42\0\1\170\50\0\5\240\1\315\1\316\1\240\1\317"+
    "\47\240\35\0\1\320\57\0\1\321\43\0\1\322\37\0"+
    "\2\3\13\0\5\3\1\0\6\3\1\0\2\3\1\321"+
    "\10\3\1\0\3\3\7\0\2\3\13\0\3\3\1\323"+
    "\1\3\1\0\6\3\1\0\2\3\1\0\10\3\1\0"+
    "\3\3\25\0\1\324\41\0\2\3\13\0\1\3\1\325"+
    "\3\3\1\0\6\3\1\0\2\3\1\0\10\3\1\0"+
    "\3\3\7\0\2\3\13\0\3\3\1\326\1\3\1\0"+
    "\6\3\1\0\2\3\1\0\10\3\1\0\3\3\7\0"+
    "\2\3\13\0\5\3\1\0\2\3\1\327\3\3\1\0"+
    "\2\3\1\0\10\3\1\0\3\3\7\0\2\3\13\0"+
    "\5\3\1\0\6\3\1\0\2\3\1\0\6\3\1\330"+
    "\1\3\1\0\3\3\46\0\1\331\20\0\2\3\13\0"+
    "\5\3\1\0\6\3\1\0\2\3\1\0\2\3\1\332"+
    "\5\3\1\0\3\3\51\0\1\333\54\0\1\334\53\0"+
    "\1\335\42\0\1\336\1\337\5\0\1\340\50\0\1\341"+
    "\1\0\1\342\10\0\2\343\56\0\2\344\53\0\1\345"+
    "\73\0\1\346\33\0\1\347\74\0\1\350\24\0\2\3"+
    "\13\0\5\3\1\0\6\3\1\0\1\3\1\351\1\0"+
    "\10\3\1\0\3\3\42\0\1\352\24\0\2\3\13\0"+
    "\5\3\1\0\6\3\1\0\1\3\1\353\1\0\10\3"+
    "\1\0\3\3\6\0\11\157\1\306\1\354\45\157\11\0"+
    "\1\307\1\354\66\0\1\355\50\0\1\356\105\0\1\357"+
    "\53\0\1\360\50\0\1\361\14\0\1\362\15\0\5\240"+
    "\1\315\1\363\1\240\1\364\54\240\1\315\1\316\1\240"+
    "\1\364\47\240\24\0\1\365\64\0\1\366\50\0\1\367"+
    "\36\0\2\3\13\0\4\3\1\370\1\0\6\3\1\0"+
    "\2\3\1\0\10\3\1\0\3\3\45\0\1\371\21\0"+
    "\2\3\13\0\5\3\1\0\6\3\1\0\2\3\1\0"+
    "\1\3\1\372\6\3\1\0\3\3\7\0\2\3\13\0"+
    "\3\3\1\373\1\3\1\0\6\3\1\0\2\3\1\0"+
    "\10\3\1\0\3\3\7\0\2\3\13\0\1\3\1\374"+
    "\3\3\1\0\6\3\1\0\2\3\1\0\10\3\1\0"+
    "\3\3\40\0\2\375\52\0\1\376\61\0\1\377\70\0"+
    "\1\u0100\36\0\1\u0101\104\0\1\u0102\40\0\1\u0103\61\0"+
    "\1\u0104\46\0\1\u0105\64\0\1\u0106\67\0\1\u0107\61\0"+
    "\1\u0108\45\0\1\u0109\61\0\1\u010a\52\0\1\u010b\36\0"+
    "\5\240\1\315\2\316\1\364\47\240\24\0\1\u010c\14\0"+
    "\1\u010d\50\0\2\u010e\64\0\1\u010f\20\0\2\3\13\0"+
    "\5\3\1\0\6\3\1\0\2\3\1\0\2\3\1\u0110"+
    "\5\3\1\0\3\3\7\0\2\3\13\0\5\3\1\0"+
    "\6\3\1\0\2\3\1\0\7\3\1\u0111\1\0\3\3"+
    "\42\0\1\u0112\63\0\1\u0113\36\0\1\u0114\57\0\1\u0115"+
    "\70\0\1\u0116\55\0\1\u0117\73\0\1\u0118\61\0\1\u0119"+
    "\63\0\1\u011a\41\0\2\u011b\45\0\1\u011c\55\0\1\u011d"+
    "\57\0\1\u011e\67\0\1\u011f\52\0\1\u0120\52\0\2\u0121"+
    "\56\0\2\u0122\75\0\1\u0123\24\0\2\3\13\0\5\3"+
    "\1\0\2\3\1\u0124\3\3\1\0\2\3\1\0\10\3"+
    "\1\0\3\3\42\0\1\u0125\57\0\1\u0126\47\0\1\u0127"+
    "\77\0\1\u0128\32\0\1\u0129\100\0\1\u012a\47\0\1\u012b"+
    "\55\0\1\u012c\52\0\1\u012d\76\0\1\u012e\47\0\1\u012f"+
    "\66\0\1\u0130\40\0\1\u0131\67\0\1\u0132\72\0\1\u0133"+
    "\31\0\2\u0134\53\0\1\u0135\46\0\2\3\13\0\5\3"+
    "\1\0\6\3\1\0\2\3\1\0\2\3\1\u0136\5\3"+
    "\1\0\3\3\27\0\1\u0137\57\0\1\u0138\64\0\1\u0139"+
    "\75\0\1\u013a\53\0\1\u013b\53\0\1\u013c\57\0\1\u013d"+
    "\63\0\1\u013e\40\0\1\u013f\50\0\1\u0140\105\0\1\u0141"+
    "\31\0\1\u0142\67\0\1\u0143\56\0\1\u0144\55\0\1\u0145"+
    "\52\0\1\u0146\103\0\1\u0147\33\0\1\u0148\112\0\1\u0149"+
    "\31\0\1\u014a\66\0\1\u014b\70\0\1\u014c\60\0\1\u014d"+
    "\57\0\1\u014e\31\0\1\u014f\45\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[12768];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\22\1\4\11\2\0\1\11"+
    "\11\0\1\1\2\0\15\1\1\0\1\1\1\0\2\1"+
    "\1\0\1\11\7\1\7\0\1\11\1\1\4\0\3\1"+
    "\1\0\6\1\1\0\3\1\1\0\1\1\2\0\3\1"+
    "\1\0\5\1\5\0\1\11\10\0\3\1\1\0\6\1"+
    "\1\0\3\1\1\0\1\1\2\0\2\1\1\0\1\1"+
    "\1\0\4\1\3\0\1\11\6\0\1\11\2\0\2\1"+
    "\1\0\5\1\1\11\3\1\1\0\1\1\1\11\11\0"+
    "\2\1\1\0\1\1\1\0\4\1\15\0\1\1\1\0"+
    "\4\1\1\11\1\1\4\0\2\11\7\0\1\11\1\1"+
    "\1\11\1\1\1\11\1\0\2\11\4\0\1\1\2\0"+
    "\1\11\1\1\1\0\3\1\22\0\1\11\2\1\3\0"+
    "\1\1\15\0\1\11\1\1\1\0\1\11\2\0\1\11"+
    "\1\1\1\0\1\11\2\0\1\11\5\0\1\11\1\1"+
    "\1\0\1\11\2\0\3\11\2\0\1\11\1\0\2\11"+
    "\1\0\2\11\1\0\1\11\4\0\1\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[335];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
public String lexeme;



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexicoCHTML(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 272) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { //return new Symbol(sym.ERROR, yycolumn, yyline,new String(yytext()));
//ejecutar.Errores.agregarError(yytext(), "Error Lexico", "No pertenece al lenguaje",0,0);
            }
          case 65: break;
          case 2: 
            { lexeme=yytext(); return new Symbol(sym.id, yycolumn, yyline,new String(yytext()));
            }
          case 66: break;
          case 3: 
            { lexeme=yytext(); return new Symbol(sym.entero, yycolumn, yyline,new String(yytext()));
            }
          case 67: break;
          case 4: 
            { /*Ignore*/
            }
          case 68: break;
          case 5: 
            { return new Symbol(sym.parentesisA, yycolumn, yyline,new String(yytext()));
            }
          case 69: break;
          case 6: 
            { return new Symbol(sym.parentesisC, yycolumn, yyline,new String(yytext()));
            }
          case 70: break;
          case 7: 
            { return new Symbol(sym.puntoComa, yycolumn, yyline,new String(yytext()));
            }
          case 71: break;
          case 8: 
            { return new Symbol(sym.igual, yycolumn, yyline,new String(yytext()));
            }
          case 72: break;
          case 9: 
            { lexeme=yytext(); return new Symbol(sym.cadena ,yycolumn, yyline,new String(yytext()));
            }
          case 73: break;
          case 10: 
            { return new Symbol(sym.cb, yycolumn, yyline,new String(yytext()));
            }
          case 74: break;
          case 11: 
            { return new Symbol(sym.ct, yycolumn, yyline,new String(yytext()));
            }
          case 75: break;
          case 12: 
            { return new Symbol(sym.idd, yycolumn, yyline,new String(yytext()));
            }
          case 76: break;
          case 13: 
            { lexeme=yytext(); return new Symbol(sym.decimal, yycolumn, yyline,new String(yytext()));
            }
          case 77: break;
          case 14: 
            { lexeme=yytext(); return new Symbol(sym.prueba ,yycolumn, yyline,new String(yytext()));
            }
          case 78: break;
          case 15: 
            { return new Symbol(sym.cjs, yycolumn, yyline, new String(yytext()));
            }
          case 79: break;
          case 16: 
            { return new Symbol(sym.alto, yycolumn, yyline,new String(yytext()));
            }
          case 80: break;
          case 17: 
            { return new Symbol(sym.ruta, yycolumn, yyline, new String(yytext()));
            }
          case 81: break;
          case 18: 
            { return new Symbol(sym.caja, yycolumn, yyline,new String(yytext()));
            }
          case 82: break;
          case 19: 
            { return new Symbol(sym.ccss, yycolumn, yyline, new String(yytext()));
            }
          case 83: break;
          case 20: 
            { lexeme=yytext(); return new Symbol(sym.cadenasin ,yycolumn, yyline,new String(yytext()));
            }
          case 84: break;
          case 21: 
            { return new Symbol(sym.ancho, yycolumn, yyline,new String(yytext()));
            }
          case 85: break;
          case 22: 
            { return new Symbol(sym.boton, yycolumn, yyline, new String(yytext()));
            }
          case 86: break;
          case 23: 
            { return new Symbol(sym.click, yycolumn, yyline, new String(yytext()));
            }
          case 87: break;
          case 24: 
            { return new Symbol(sym.tabla, yycolumn, yyline,new String(yytext()));
            }
          case 88: break;
          case 25: 
            { return new Symbol(sym.texto, yycolumn, yyline,new String(yytext()));
            }
          case 89: break;
          case 26: 
            { return new Symbol(sym.filt, yycolumn, yyline,new String(yytext()));
            }
          case 90: break;
          case 27: 
            { return new Symbol(sym.fondo, yycolumn, yyline, new String(yytext()));
            }
          case 91: break;
          case 28: 
            { return new Symbol(sym.panel, yycolumn, yyline,new String(yytext()));
            }
          case 92: break;
          case 29: 
            { return new Symbol(sym.grupo, yycolumn, yyline,new String(yytext()));
            }
          case 93: break;
          case 30: 
            { return new Symbol(sym.valor, yycolumn, yyline,new String(yytext()));
            }
          case 94: break;
          case 31: 
            { return new Symbol(sym.enlace, yycolumn, yyline,new String(yytext()));
            }
          case 95: break;
          case 32: 
            { return new Symbol(sym.titulo, yycolumn, yyline,new String(yytext()));
            }
          case 96: break;
          case 33: 
            { return new Symbol(sym.fincb, yycolumn, yyline,new String(yytext()));
            }
          case 97: break;
          case 34: 
            { return new Symbol(sym.finct, yycolumn, yyline,new String(yytext()));
            }
          case 98: break;
          case 35: 
            { return new Symbol(sym.imagen, yycolumn, yyline, new String(yytext()));
            }
          case 99: break;
          case 36: 
            { return new Symbol(sym.opcion, yycolumn, yyline,new String(yytext()));
            }
          case 100: break;
          case 37: 
            { 
            }
          case 101: break;
          case 38: 
            { return new Symbol(sym.chtml, yycolumn, yyline, new String(yytext()));
            }
          case 102: break;
          case 39: 
            { return new Symbol(sym.cuerpo, yycolumn, yyline, new String(yytext()));
            }
          case 103: break;
          case 40: 
            { lexeme=yytext(); return new Symbol(sym.cadenasalto ,yycolumn, yyline,new String(yytext()));
            }
          case 104: break;
          case 41: 
            { return new Symbol(sym.spinner, yycolumn, yyline,new String(yytext()));
            }
          case 105: break;
          case 42: 
            { return new Symbol(sym.textoa, yycolumn, yyline,new String(yytext()));
            }
          case 106: break;
          case 43: 
            { return new Symbol(sym.alineado, yycolumn, yyline,new String(yytext()));
            }
          case 107: break;
          case 44: 
            { return new Symbol(sym.fincaja, yycolumn, yyline,new String(yytext()));
            }
          case 108: break;
          case 45: 
            { return new Symbol(sym.saltofin, yycolumn, yyline,new String(yytext()));
            }
          case 109: break;
          case 46: 
            { return new Symbol(sym.finboton, yycolumn, yyline, new String(yytext()));
            }
          case 110: break;
          case 47: 
            { return new Symbol(sym.fintabla, yycolumn, yyline,new String(yytext()));
            }
          case 111: break;
          case 48: 
            { return new Symbol(sym.fintexto, yycolumn, yyline,new String(yytext()));
            }
          case 112: break;
          case 49: 
            { return new Symbol(sym.finfilt, yycolumn, yyline,new String(yytext()));
            }
          case 113: break;
          case 50: 
            { return new Symbol(sym.finpanel, yycolumn, yyline,new String(yytext()));
            }
          case 114: break;
          case 51: 
            { return new Symbol(sym.fincjs, yycolumn, yyline, new String(yytext()));
            }
          case 115: break;
          case 52: 
            { return new Symbol(sym.cajatexto, yycolumn, yyline,new String(yytext()));
            }
          case 116: break;
          case 53: 
            { return new Symbol(sym.finenlace, yycolumn, yyline,new String(yytext()));
            }
          case 117: break;
          case 54: 
            { return new Symbol(sym.fintitulo, yycolumn, yyline,new String(yytext()));
            }
          case 118: break;
          case 55: 
            { return new Symbol(sym.finimagen, yycolumn, yyline, new String(yytext()));
            }
          case 119: break;
          case 56: 
            { return new Symbol(sym.finopcion, yycolumn, yyline,new String(yytext()));
            }
          case 120: break;
          case 57: 
            { return new Symbol(sym.finchtml, yycolumn, yyline, new String(yytext()));
            }
          case 121: break;
          case 58: 
            { return new Symbol(sym.finccss, yycolumn, yyline, new String(yytext()));
            }
          case 122: break;
          case 59: 
            { return new Symbol(sym.finspinner, yycolumn, yyline,new String(yytext()));
            }
          case 123: break;
          case 60: 
            { return new Symbol(sym.fintextoa, yycolumn, yyline,new String(yytext()));
            }
          case 124: break;
          case 61: 
            { return new Symbol(sym.encabezado, yycolumn, yyline, new String(yytext()));
            }
          case 125: break;
          case 62: 
            { return new Symbol(sym.fincuerpo, yycolumn, yyline, new String(yytext()));
            }
          case 126: break;
          case 63: 
            { return new Symbol(sym.fincajatexto, yycolumn, yyline,new String(yytext()));
            }
          case 127: break;
          case 64: 
            { return new Symbol(sym.finencabezado, yycolumn, yyline, new String(yytext()));
            }
          case 128: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
