package chtml;

import java_cup.runtime.*;
import usacweb.Datos;
init with {:

:};
parser code
{:
// METODOS Y VARIABLES GLOBALES DEL PARSER, PUEDEN SER PUBLICAS O PRIVADAS

 
public void syntax_error(Symbol s){
/**Metodo al que se llama automaticamente ante algun error sintactico.*/
        System.out.println("Error Sintactico en la Linea " + (s.right+1) +" Columna "+s.left+ ". Identificador " +s.value + " no reconocido." );
        int linea = s.right+1; int columna = s.left; 
        String texto = "Identificador " +s.value + " no reconocido.";
        Datos.agregarError("Error Sintactico",texto, linea,columna);

}            
public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
/**Metodo al que se llama en el momento en que ya no es posible una recuperacion de errores.*/
        System.out.println("Error Sintactico no recuperable en la Linea " + (s.right+1)+ " Columna "+s.left+". Identificador " + s.value + " no reconocido.");
}
:}

action code
{:
:}

terminal String chtml,finchtml,encabezado,finencabezado,cjs,fincjs,ruta,ccss,finccss,fondo,cuerpo,fincuerpo,titulo,fintitulo,
panel,finpanel,cajatexto,fincajatexto,texto,fintexto,click,imagen,finimagen,boton,finboton,enlace,finenlace,tabla,fintabla,
filt,finfilt,cb,fincb,ct,finct,textoa,fintextoa,caja,fincaja,opcion,finopcion,valor,spinner,finspinner,saltofin,grupo,alto,
ancho,alineado,idd,id,entero,decimal,puntoComa,parentesisA,parentesisC,cadenacon,cadena,cadenasin,igual,mayor,menor;

non terminal Caracter INICIO,RAIZ,ENCABEZADO,CUERPO,INFORMACION,INFO,CONTENIDO,HTML,ETIQUETAS,ETIQUETA,LISTAFILA,
PANEL,TEXTO,IMAGEN,BOTON,ENLACE,TABLA,CAJATEXTO,CAJA,ELEMENTOS,ELEMENTO,TEXTOA,OPCION,SPINNER,FILA,CELDAS,CELDA,OPCIONES,R;

//precedence left mas, menos;

start with INICIO;

INICIO::=RAIZ:r{:
     chtml.NODO = r.nodo;
:};


RAIZ::=  chtml:i HTML:n finchtml{:
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("RAIZ");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo); E.insertar(new NodoCHTML("finhtml"));
    RESULT.nodo = E;
:};


HTML ::= ENCABEZADO:e CUERPO:c{:
    NodoCHTML E = new NodoCHTML("HTML");
    RESULT = new Caracter();
    E.insertar(e.nodo); E.insertar(c.nodo);
    RESULT.nodo = E;
:}
|ENCABEZADO:e {:
    NodoCHTML E = new NodoCHTML("HTML");
    RESULT = new Caracter();
    E.insertar(e.nodo);
    RESULT.nodo = E;
:};


ENCABEZADO::= encabezado:i INFORMACION:n finencabezado{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ENCABEZADO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo); E.insertar(new NodoCHTML("finencabezado"));
    RESULT.nodo = E;
:}
|encabezado:i finencabezado{://2
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ENCABEZADO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("finencabezado"));
    RESULT.nodo = E;
:}
|error:i finencabezado{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:};


INFORMACION::=INFORMACION:e INFO:c{:
    NodoCHTML E = new NodoCHTML("INFORMACION");
    RESULT = new Caracter();
    E.insertar(e.nodo); E.insertar(c.nodo);
    RESULT.nodo = E;
:}
|INFO:c{:
    NodoCHTML E = new NodoCHTML("INFORMACION");
    RESULT = new Caracter();
    E.insertar(c.nodo);
    RESULT.nodo = E;
:};


INFO::= cjs:i ruta igual cadena:n puntoComa mayor fincjs {://4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("INFO");
    E.insertar(new NodoCHTML(i)); E.insertar(new NodoCHTML("ruta=")); E.insertar(new NodoCHTML(n)); E.insertar(new NodoCHTML(";>fincjs"));
    RESULT.nodo = E;
:}
| ccss:i ruta igual cadena:n puntoComa  mayor finccss {://4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("INFO");
    E.insertar(new NodoCHTML(i)); E.insertar(new NodoCHTML("ruta=")); E.insertar(new NodoCHTML(n)); E.insertar(new NodoCHTML(";>finccss"));
    RESULT.nodo = E;
:}
| titulo:i cadenasin:n fintitulo {://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("INFO");
    E.insertar(new NodoCHTML(i));  E.insertar(new NodoCHTML(n)); E.insertar(new NodoCHTML("fintitulo"));
    RESULT.nodo = E;
:}
|error:i fincjs{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:}
|error:i finccss{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:}
|error:i fintitulo{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:};


CUERPO::= cuerpo:i ELEMENTOS:n mayor ETIQUETAS:e fincuerpo {: //5
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CUERPO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo);  E.insertar(new NodoCHTML(">")); E.insertar(e.nodo);E.insertar(new NodoCHTML("<fincuerpo>"));
    RESULT.nodo = E;
:}
| cuerpo:i ELEMENTOS:n mayor fincuerpo {: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CUERPO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo); 
    E.insertar(new NodoCHTML(">")); E.insertar(new NodoCHTML("<fincuerpo>"));
    RESULT.nodo = E;
:}
| cuerpo:i mayor ETIQUETAS:e  fincuerpo{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CUERPO");
    E.insertar(new NodoCHTML(i,iright,ileft));  E.insertar(new NodoCHTML(">")); E.insertar(e.nodo);E.insertar(new NodoCHTML("<fincuerpo>"));
    RESULT.nodo = E;
:} 
| cuerpo:i mayor fincuerpo{: //2
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CUERPO");
    E.insertar(new NodoCHTML(i,iright,ileft));E.insertar(new NodoCHTML("><fincuerpo>"));
    RESULT.nodo = E;
:}
|error:i fincuerpo{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:};


ETIQUETAS::=ETIQUETAS:t ETIQUETA:e{:
    NodoCHTML E = new NodoCHTML("ETIQUETAS");
    RESULT = new Caracter();
    E.insertar(t.nodo); E.insertar(e.nodo);
    RESULT.nodo = E;
:}
|ETIQUETA:e{:
    NodoCHTML E = new NodoCHTML("ETIQUETAS");
    RESULT = new Caracter();
    E.insertar(e.nodo);
    RESULT.nodo = E;
:}; 


ETIQUETA::=PANEL:e{:
    NodoCHTML E = new NodoCHTML("ETIQUETA");
    RESULT = new Caracter();
    E.insertar(e.nodo);
    RESULT.nodo = E;
:}
|TEXTO:e{:
    NodoCHTML E = new NodoCHTML("ETIQUETA");
    RESULT = new Caracter();
    E.insertar(e.nodo);
    RESULT.nodo = E;
:}
|IMAGEN:e{:
    NodoCHTML E = new NodoCHTML("ETIQUETA");
    RESULT = new Caracter();
    E.insertar(e.nodo);
    RESULT.nodo = E;
:}
|BOTON:e{:
    NodoCHTML E = new NodoCHTML("ETIQUETA");
    RESULT = new Caracter();
    E.insertar(e.nodo);
    RESULT.nodo = E;
:}
|ENLACE:e{:
    NodoCHTML E = new NodoCHTML("ETIQUETA");
    RESULT = new Caracter();
    E.insertar(e.nodo);
    RESULT.nodo = E;
:}
|TABLA:e{:
    NodoCHTML E = new NodoCHTML("ETIQUETA");
    RESULT = new Caracter();
    E.insertar(e.nodo);
    RESULT.nodo = E;
:}
|TEXTOA:e{:
    NodoCHTML E = new NodoCHTML("ETIQUETA");
    RESULT = new Caracter();
    E.insertar(e.nodo);
    RESULT.nodo = E;
:}
|CAJATEXTO:e{:
    NodoCHTML E = new NodoCHTML("ETIQUETA");
    RESULT = new Caracter();
    E.insertar(e.nodo);
    RESULT.nodo = E;
:}
|CAJA:e{:
    NodoCHTML E = new NodoCHTML("ETIQUETA");
    RESULT = new Caracter();
    E.insertar(e.nodo);
    RESULT.nodo = E;
:}
|OPCION:e{:
    NodoCHTML E = new NodoCHTML("ETIQUETA");
    RESULT = new Caracter();
    E.insertar(e.nodo);
    RESULT.nodo = E;
:}
|SPINNER:e{:
    NodoCHTML E = new NodoCHTML("ETIQUETA");
    RESULT = new Caracter();
    E.insertar(e.nodo);
    RESULT.nodo = E;
:}
|saltofin:e{:
    NodoCHTML E = new NodoCHTML("ETIQUETA");
    RESULT = new Caracter();
    E.insertar(new NodoCHTML("saltofin"));
    RESULT.nodo = E;
:};


PANEL::= panel:i ELEMENTOS:n mayor ETIQUETAS:e finpanel{: //5
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("PANEL");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo);  E.insertar(new NodoCHTML(">")); E.insertar(e.nodo);E.insertar(new NodoCHTML("<finpanel>"));
    RESULT.nodo = E;
:}
| panel:i ELEMENTOS:n mayor finpanel{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("PANEL");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo);  E.insertar(new NodoCHTML(">"));E.insertar(new NodoCHTML("<finpanel>"));
    RESULT.nodo = E;
:}
| panel:i mayor ETIQUETAS:e finpanel{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("PANEL");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML(">")); E.insertar(e.nodo);E.insertar(new NodoCHTML("<finpanel>"));
    RESULT.nodo = E;
:} 
| panel:i mayor finpanel{: //2
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("PANEL");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("><finpanel>"));
    RESULT.nodo = E;
:}
|error:i finpanel{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:};


TEXTO::= texto:i ELEMENTOS:n cadenacon:s fintexto{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("TEXTO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo);  E.insertar(new NodoCHTML(s)); E.insertar(new NodoCHTML("finboton>"));
    RESULT.nodo = E;
:}
|texto:i ELEMENTOS:n cadenasin:s fintexto{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("TEXTO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo);  E.insertar(new NodoCHTML(s)); E.insertar(new NodoCHTML("finboton>"));
    RESULT.nodo = E;
:}
|texto:i ELEMENTOS:n mayor menor fintexto{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("TEXTO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo); E.insertar(new NodoCHTML("><finboton>"));
    RESULT.nodo = E;
:}
|texto:i cadenacon:s fintexto{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("TEXTO");
    E.insertar(new NodoCHTML(i,iright,ileft));  E.insertar(new NodoCHTML(s)); E.insertar(new NodoCHTML("finboton>"));
    RESULT.nodo = E;
:}
|texto:i mayor menor fintexto{: //2
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("TEXTO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("><finboton>"));
    RESULT.nodo = E;
:}
|error:i fintexto{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:};



IMAGEN::= imagen:i ELEMENTOS:n cadenasin:s finimagen{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("IMAGEN");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo);  E.insertar(new NodoCHTML(s)); E.insertar(new NodoCHTML("finimagen>"));
    RESULT.nodo = E;
:}
|imagen:i ELEMENTOS:n mayor menor finimagen{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("IMAGEN");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo); E.insertar(new NodoCHTML("><finimagen>"));
    RESULT.nodo = E;
:}
|imagen:i cadenasin:s finimagen{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("IMAGEN");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML(s)); E.insertar(new NodoCHTML("finimagen>"));
    RESULT.nodo = E;
:}
|imagen:i mayor menor finimagen{: //2
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("IMAGEN");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("><finimagen>"));
    RESULT.nodo = E;
:}
|error:i finimagen{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:};


ELEMENTOS::= ELEMENTOS:t ELEMENTO:e{:
    NodoCHTML E = new NodoCHTML("ELEMENTOS");
    RESULT = new Caracter();
    E.insertar(t.nodo); E.insertar(e.nodo);
    RESULT.nodo = E;
:}
|ELEMENTO:e{:
    NodoCHTML E = new NodoCHTML("ELEMENTOS");
    RESULT = new Caracter();
    E.insertar(e.nodo);
    RESULT.nodo = E;
:};


ELEMENTO::= ruta:i igual cadena:n puntoComa{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ELEMENTO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("=")); E.insertar(new NodoCHTML(n,nright,nleft)); E.insertar(new NodoCHTML(";"));
    RESULT.nodo = E;
:}
|click:i igual cadena:n puntoComa{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ELEMENTO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("=")); E.insertar(new NodoCHTML(n,nright,nleft)); E.insertar(new NodoCHTML(";"));
    RESULT.nodo = E;
:}
|idd:i igual cadena:n puntoComa{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ELEMENTO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("=")); E.insertar(new NodoCHTML(n,nright,nleft)); E.insertar(new NodoCHTML(";"));
    RESULT.nodo = E;
:}
|grupo:i igual cadena:n puntoComa{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ELEMENTO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("=")); E.insertar(new NodoCHTML(n,nright,nleft)); E.insertar(new NodoCHTML(";"));
    RESULT.nodo = E;
:}
|alto:i igual cadena:n puntoComa{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ELEMENTO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("=")); E.insertar(new NodoCHTML(n,nright,nleft)); E.insertar(new NodoCHTML(";"));
    RESULT.nodo = E;
:}
|ancho:i igual cadena:n puntoComa{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ELEMENTO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("=")); E.insertar(new NodoCHTML(n,nright,nleft)); E.insertar(new NodoCHTML(";"));
    RESULT.nodo = E;
:}
|alineado:i igual cadena:n puntoComa{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ELEMENTO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("=")); E.insertar(new NodoCHTML(n,nright,nleft)); E.insertar(new NodoCHTML(";"));
    RESULT.nodo = E;
:}
|valor:i igual cadena:n puntoComa{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ELEMENTO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("=")); E.insertar(new NodoCHTML(n,nright,nleft)); E.insertar(new NodoCHTML(";"));
    RESULT.nodo = E;
:}
|fondo:i igual cadena:n puntoComa{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ELEMENTO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("=")); E.insertar(new NodoCHTML(n,nright,nleft)); E.insertar(new NodoCHTML(";"));
    RESULT.nodo = E;
:}
|error:i puntoComa{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:};


BOTON::= boton:i ELEMENTOS:n cadenasin:s finboton{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("BOTON");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo);  E.insertar(new NodoCHTML(s)); E.insertar(new NodoCHTML("finboton>"));
    RESULT.nodo = E;
:}
|boton:i ELEMENTOS:n mayor menor finboton{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("BOTON");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo); E.insertar(new NodoCHTML("><finboton>"));
    RESULT.nodo = E;
:}
|boton:i cadenasin:s finboton{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("BOTON");
    E.insertar(new NodoCHTML(i,iright,ileft));  E.insertar(new NodoCHTML(s)); E.insertar(new NodoCHTML("finboton>"));
    RESULT.nodo = E;
:}
|boton:i mayor menor finboton{: //2
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("BOTON");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("><finboton>"));
    RESULT.nodo = E;
:}
|error:i finboton{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:};


ENLACE::= enlace:i ELEMENTOS:n cadenacon:s finenlace{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ENLACE");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo);  E.insertar(new NodoCHTML(s)); E.insertar(new NodoCHTML("finenlace>"));
    RESULT.nodo = E;
:}
|enlace:i ELEMENTOS:n mayor menor finenlace{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ENLACE");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo);  E.insertar(new NodoCHTML("><finenlace>"));
    RESULT.nodo = E;
:}
|enlace:i cadenacon:s finenlace{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ENLACE");
    E.insertar(new NodoCHTML(i,iright,ileft));  E.insertar(new NodoCHTML(s)); E.insertar(new NodoCHTML("finenlace>"));
    RESULT.nodo = E;
:}
|enlace:i mayor menor finenlace{: //2
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ENLACE");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("><finenlace>"));
    RESULT.nodo = E;
:}
|error:i finenlace{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:};


TABLA::= tabla:i ELEMENTOS:n mayor LISTAFILA:e fintabla{: //5
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("TABLA");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo);  E.insertar(new NodoCHTML(">")); E.insertar(e.nodo);E.insertar(new NodoCHTML("<fintabla>"));
    RESULT.nodo = E;
:}
|tabla:i ELEMENTOS:n mayor fintabla{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("TABLA");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo); E.insertar(new NodoCHTML(">")); E.insertar(new NodoCHTML("<fintabla>"));
    RESULT.nodo = E;
:}
|tabla:i mayor LISTAFILA:e fintabla{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("TABLA");
    E.insertar(new NodoCHTML(i,iright,ileft));  E.insertar(new NodoCHTML(">")); E.insertar(e.nodo);E.insertar(new NodoCHTML("<fintabla>"));
    RESULT.nodo = E;
:}
|tabla:i mayor fintabla{: //2
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("TABLA");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("><fintabla>"));
    RESULT.nodo = E;
:}
|error:i fintabla{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:};


LISTAFILA::=LISTAFILA:n FILA:e{: //2
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("LISTAFILA");
    E.insertar(n.nodo); E.insertar(e.nodo);
    RESULT.nodo = E;
:}
|FILA:e{: 
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("LISTAFILA");
    E.insertar(e.nodo);
    RESULT.nodo = E;
:};


FILA::= filt:i CELDAS:e finfilt{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("FILA");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(e.nodo); E.insertar(new NodoCHTML("<finfilt>"));
    RESULT.nodo = E;
:}
|filt:i finfilt{: //2
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("FILA");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("<finfilt>"));
    RESULT.nodo = E;
:}
|error:i finfilt{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:};


CELDAS::= CELDAS:n CELDA:e{: //2
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CELDAS");
    E.insertar(n.nodo); E.insertar(e.nodo);
    RESULT.nodo = E;
:}
|CELDA:e{: //2
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CELDAS");
    E.insertar(e.nodo);
    RESULT.nodo = E;
:};


CELDA::= cb:i cadenasin:s fincb{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CELDA");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML(s,sright,sleft)); E.insertar(new NodoCHTML("fincb>"));
    RESULT.nodo = E;
:}
|cb:i mayor menor fincb{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CELDA");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("><")); E.insertar(new NodoCHTML("fincb>"));
    RESULT.nodo = E;
:}
|ct:i CONTENIDO:n finct{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CELDA");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo); E.insertar(new NodoCHTML("finct>"));
    RESULT.nodo = E;
:}
|ct:i mayor menor finct{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CELDA");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("><")); E.insertar(new NodoCHTML("fincb>"));
    RESULT.nodo = E;
:}
|error:i fincb{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:}
|error:i finct{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:};


CONTENIDO::= cadenasin:s{: //1
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CONTENIDO");
    E.insertar(new NodoCHTML(s));
    RESULT.nodo = E;
:}
|mayor IMAGEN:n menor{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CONTENIDO");
    E.insertar(new NodoCHTML(">")); E.insertar(n.nodo); E.insertar(new NodoCHTML("<"));
    RESULT.nodo = E;
:}
|mayor BOTON:n menor{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CONTENIDO");
    E.insertar(new NodoCHTML(">")); E.insertar(n.nodo); E.insertar(new NodoCHTML("<"));
    RESULT.nodo = E;
:};


TEXTOA::= textoa:i ELEMENTOS:n cadenacon:s fintextoa{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("TEXTOA");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo);  E.insertar(new NodoCHTML(s)); E.insertar(new NodoCHTML("finboton>"));
    RESULT.nodo = E;
:}
|textoa:i ELEMENTOS:n mayor menor fintextoa{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("TEXTOA");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo); E.insertar(new NodoCHTML("><finboton>"));
    RESULT.nodo = E;
:}
|textoa:i cadenacon:s fintextoa{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("TEXTOA");
    E.insertar(new NodoCHTML(i,iright,ileft));  E.insertar(new NodoCHTML(s)); E.insertar(new NodoCHTML("finboton>"));
    RESULT.nodo = E;
:}
|textoa:i mayor menor fintextoa{: //2
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("TEXTOA");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("><finboton>"));
    RESULT.nodo = E;
:}
|error:i fintextoa{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:};


CAJATEXTO::=cajatexto:i ELEMENTOS:n cadenasin:e fincajatexto{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CAJATEXTO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo);  E.insertar(new NodoCHTML(e)); E.insertar(new NodoCHTML("fincajatexto>"));
    RESULT.nodo = E;
:}
|cajatexto:i ELEMENTOS:n mayor menor fincajatexto{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CAJATEXTO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo);  E.insertar(new NodoCHTML("><fincajatexto>"));
    RESULT.nodo = E;
:}
|cajatexto:i cadenasin:e fincajatexto{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CAJATEXTO");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML(e)); E.insertar(new NodoCHTML("fincajatexto>"));
    RESULT.nodo = E;
:}
|cajatexto:i mayor menor fincajatexto{: //2
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CAJATEXTO");
    E.insertar(new NodoCHTML(i,iright,ileft));E.insertar(new NodoCHTML("><fincajatexto>"));
    RESULT.nodo = E;
:}
|error:i fincajatexto{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:};


CAJA::=caja:i ELEMENTOS:n mayor OPCIONES:e fincaja{: //5
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CAJA");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo); E.insertar(new NodoCHTML(">")); E.insertar(e.nodo);E.insertar(new NodoCHTML("<fincaja>"));
    RESULT.nodo = E;
:}
|caja:i ELEMENTOS:n mayor fincaja{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CAJA");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo); E.insertar(new NodoCHTML(">"));E.insertar(new NodoCHTML("<fincaja>"));
    RESULT.nodo = E;
:}
|caja:i mayor OPCIONES:e fincaja{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CAJA");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML(">")); E.insertar(e.nodo);E.insertar(new NodoCHTML("<fincaja>"));
    RESULT.nodo = E;
:}
|caja:i mayor fincaja{: //2
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("CAJA");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("><fincaja>"));
    RESULT.nodo = E;
:}
|error:i fincaja{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:};


OPCIONES::= OPCIONES:n OPCION:e{: //2
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("OPCIONES");
    E.insertar(n.nodo); E.insertar(e.nodo);
    RESULT.nodo = E;
:}
|OPCION:e{: //1
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("OPCIONES");
    E.insertar(e.nodo);
    RESULT.nodo = E;
:};


OPCION::=opcion:i ELEMENTOS:n cadenasin:e finopcion{: //5
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("OPCION");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo); E.insertar(new NodoCHTML(e)); E.insertar(new NodoCHTML("finopcion>"));
    RESULT.nodo = E;
:}
|opcion:i ELEMENTOS:n mayor menor finopcion{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("OPCION");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo); E.insertar(new NodoCHTML("><finopcion>"));
    RESULT.nodo = E;
:}
|opcion:i cadenasin:e finopcion{: //3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("OPCION");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML(e)); E.insertar(new NodoCHTML("finopcion>"));
    RESULT.nodo = E;
:}
|opcion:i mayor menor finopcion{: //2
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("OPCION");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("><finopcion>"));
    RESULT.nodo = E;
:}
|error:i finopcion{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:};


SPINNER::= spinner:i ELEMENTOS:n cadenasin:e finspinner{: //5
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("SPINNER");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo);  E.insertar(new NodoCHTML(">")); E.insertar(new NodoCHTML(e));E.insertar(new NodoCHTML("<finspinner>"));
    RESULT.nodo = E;
:}
|spinner:i ELEMENTOS:n mayor menor finspinner{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("SPINNER");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(n.nodo);  E.insertar(new NodoCHTML(">"));E.insertar(new NodoCHTML("<finspinner>"));
    RESULT.nodo = E;
:}
|spinner:i cadenasin:e finspinner{: //4
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("SPINNER");
    E.insertar(new NodoCHTML(i,iright,ileft));  E.insertar(new NodoCHTML(">")); E.insertar(new NodoCHTML(e));E.insertar(new NodoCHTML("<finspinner>"));
    RESULT.nodo = E;
:}
|spinner:i mayor menor finspinner{: //2
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("SPINNER");
    E.insertar(new NodoCHTML(i,iright,ileft)); E.insertar(new NodoCHTML("><finspinner>"));
    RESULT.nodo = E;
:}
|error:i finspinner{://3
    RESULT = new Caracter();
    NodoCHTML E = new NodoCHTML("ERROR");
    E.insertar(new NodoCHTML((String)i)); 
    RESULT.nodo = E;
:};
