
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package chtml;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cadenacon = 58;
  public static final int ancho = 49;
  public static final int finimagen = 24;
  public static final int fondo = 11;
  public static final int fincb = 34;
  public static final int cadenasin = 60;
  public static final int finspinner = 45;
  public static final int fincaja = 40;
  public static final int imagen = 23;
  public static final int ct2 = 64;
  public static final int idd = 51;
  public static final int igual = 61;
  public static final int finct2 = 65;
  public static final int filt = 31;
  public static final int alto = 48;
  public static final int panel = 16;
  public static final int grupo = 47;
  public static final int finpanel = 17;
  public static final int alineado = 50;
  public static final int ruta = 8;
  public static final int ccss = 9;
  public static final int tabla = 29;
  public static final int chtml = 2;
  public static final int menor = 63;
  public static final int ct = 35;
  public static final int fintabla = 30;
  public static final int finchtml = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int fincajatexto = 19;
  public static final int mayor = 62;
  public static final int saltofin = 46;
  public static final int entero = 53;
  public static final int fincuerpo = 13;
  public static final int finfilt = 32;
  public static final int valor = 43;
  public static final int cuerpo = 12;
  public static final int spinner = 44;
  public static final int click = 22;
  public static final int cb = 33;
  public static final int id = 52;
  public static final int puntoComa = 55;
  public static final int finopcion = 42;
  public static final int finenlace = 28;
  public static final int opcion = 41;
  public static final int cjs = 6;
  public static final int fintitulo = 15;
  public static final int enlace = 27;
  public static final int fintextoa = 38;
  public static final int finccss = 10;
  public static final int titulo = 14;
  public static final int caja = 39;
  public static final int encabezado = 4;
  public static final int texto = 20;
  public static final int fincjs = 7;
  public static final int textoa = 37;
  public static final int fintexto = 21;
  public static final int parentesisC = 57;
  public static final int parentesisA = 56;
  public static final int cajatexto = 18;
  public static final int finct = 36;
  public static final int finencabezado = 5;
  public static final int boton = 25;
  public static final int finboton = 26;
  public static final int decimal = 54;
  public static final int cadena = 59;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "chtml",
  "finchtml",
  "encabezado",
  "finencabezado",
  "cjs",
  "fincjs",
  "ruta",
  "ccss",
  "finccss",
  "fondo",
  "cuerpo",
  "fincuerpo",
  "titulo",
  "fintitulo",
  "panel",
  "finpanel",
  "cajatexto",
  "fincajatexto",
  "texto",
  "fintexto",
  "click",
  "imagen",
  "finimagen",
  "boton",
  "finboton",
  "enlace",
  "finenlace",
  "tabla",
  "fintabla",
  "filt",
  "finfilt",
  "cb",
  "fincb",
  "ct",
  "finct",
  "textoa",
  "fintextoa",
  "caja",
  "fincaja",
  "opcion",
  "finopcion",
  "valor",
  "spinner",
  "finspinner",
  "saltofin",
  "grupo",
  "alto",
  "ancho",
  "alineado",
  "idd",
  "id",
  "entero",
  "decimal",
  "puntoComa",
  "parentesisA",
  "parentesisC",
  "cadenacon",
  "cadena",
  "cadenasin",
  "igual",
  "mayor",
  "menor",
  "ct2",
  "finct2"
  };
}

