
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cjs;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int dimv = 2;
  public static final int imprimir = 39;
  public static final int fecha = 58;
  public static final int igualDoble = 42;
  public static final int dosPuntos = 38;
  public static final int corcheteC = 34;
  public static final int corcheteA = 33;
  public static final int detener = 20;
  public static final int coma = 12;
  public static final int igual = 27;
  public static final int conteo = 57;
  public static final int caracter = 56;
  public static final int menorIgual = 26;
  public static final int dividido = 51;
  public static final int aumentar = 49;
  public static final int si = 14;
  public static final int mientras = 19;
  public static final int numero = 48;
  public static final int observador = 8;
  public static final int defecto = 18;
  public static final int menos = 22;
  public static final int menor = 24;
  public static final int EOF = 0;
  public static final int set = 9;
  public static final int mas = 21;
  public static final int verdadero = 40;
  public static final int para = 36;
  public static final int mayorIgual = 25;
  public static final int error = 1;
  public static final int mayor = 23;
  public static final int entero = 54;
  public static final int or = 29;
  public static final int por = 37;
  public static final int hora = 59;
  public static final int punto = 55;
  public static final int mensaje = 5;
  public static final int funcion = 4;
  public static final int ERROR = 47;
  public static final int llaveC = 45;
  public static final int potencia = 43;
  public static final int id = 32;
  public static final int obtener = 7;
  public static final int puntoComa = 46;
  public static final int llaveA = 44;
  public static final int falso = 41;
  public static final int caso = 17;
  public static final int disminuir = 35;
  public static final int documento = 6;
  public static final int diferente = 28;
  public static final int and = 30;
  public static final int not = 31;
  public static final int parentesisC = 11;
  public static final int atexto = 3;
  public static final int retornar = 13;
  public static final int parentesisA = 10;
  public static final int selecciona = 16;
  public static final int decimal = 53;
  public static final int modulo = 50;
  public static final int cadena = 52;
  public static final int sino = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "dimv",
  "atexto",
  "funcion",
  "mensaje",
  "documento",
  "obtener",
  "observador",
  "set",
  "parentesisA",
  "parentesisC",
  "coma",
  "retornar",
  "si",
  "sino",
  "selecciona",
  "caso",
  "defecto",
  "mientras",
  "detener",
  "mas",
  "menos",
  "mayor",
  "menor",
  "mayorIgual",
  "menorIgual",
  "igual",
  "diferente",
  "or",
  "and",
  "not",
  "id",
  "corcheteA",
  "corcheteC",
  "disminuir",
  "para",
  "por",
  "dosPuntos",
  "imprimir",
  "verdadero",
  "falso",
  "igualDoble",
  "potencia",
  "llaveA",
  "llaveC",
  "puntoComa",
  "ERROR",
  "numero",
  "aumentar",
  "modulo",
  "dividido",
  "cadena",
  "decimal",
  "entero",
  "punto",
  "caracter",
  "conteo",
  "fecha",
  "hora"
  };
}

